-- DropIndex
DROP INDEX "HourlyRate_userId_key";

-- AlterTable
ALTER TABLE "HourlyRate" ADD COLUMN     "validFrom" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "holidayMult" DOUBLE PRECISION NOT NULL DEFAULT 1.0,
ADD COLUMN     "lastReminderAt" TIMESTAMP(3),
ADD COLUMN     "nightEnd" INTEGER NOT NULL DEFAULT 6,
ADD COLUMN     "nightMult" DOUBLE PRECISION NOT NULL DEFAULT 0.2,
ADD COLUMN     "nightStart" INTEGER NOT NULL DEFAULT 21,
ADD COLUMN     "reminderEnabled" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "reminderThreshold" INTEGER NOT NULL DEFAULT 7,
ADD COLUMN     "sundayMult" DOUBLE PRECISION NOT NULL DEFAULT 0.2;

-- AlterTable
ALTER TABLE "WorkShift" ADD COLUMN     "holidayHours" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "nightHours" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "premiumPay" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "rateSnapshot" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "sundayHours" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- CreateIndex
CREATE INDEX "HourlyRate_userId_validFrom_idx" ON "HourlyRate"("userId", "validFrom");
